### ISSUE TITLE
the new version docker image is not working

### ISSUE THREAD

**Issue by TheInfamousToTo** [Impre-visible/invoicerr#111]
```
[Nest] 93  - 07/25/2025, 7:33:29 AM   ERROR [ExceptionHandler] TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at new LoginRequiredGuard (/usr/share/nginx/backend/guards/login-required.guard.js:25:52)
    at Injector.instantiateClass (/usr/share/nginx/backend/node_modules/@nestjs/core/injector/injector.js:413:19)
    at callback (/usr/share/nginx/backend/node_modules/@nestjs/core/injector/injector.js:70:45)
    at async Injector.resolveConstructorParams (/usr/share/nginx/backend/node_modules/@nestjs/core/injector/injector.js:168:24)
    at async Injector.loadInstance (/usr/share/nginx/backend/node_modules/@nestjs/core/injector/injector.js:75:13)
    at async Injector.loadInjectable (/usr/share/nginx/backend/node_modules/@nestjs/core/injector/injector.js:99:9)
    at async /usr/share/nginx/backend/node_modules/@nestjs/core/injector/instance-loader.js:80:13
    at async Promise.all (index 0)
    at async InstanceLoader.createInstancesOfInjectables (/usr/share/nginx/backend/node_modules/@nestjs/core/injector/instance-loader.js:79:9) {
  code: 'ERR_INVALID_URL',
}
  input: ''
```

here is my docker compose file 
```
services:
  invoicerr:
    image: ghcr.io/impre-visible/invoicerr:latest
    restart: unless-stopped
    ports:
      - "8870:80"
    environment:
      - DATABASE_URL=postgresql://invoicerr:invoicerr@REPLACED/invoicerr_db

      - APP_URL=https://REPLACED

      # Required for email features
      - SMTP_HOST="smtp.gmail.com"
      - SMTP_USER="REPLACED"
      - SMTP_FROM="REPLACED" # Not required if SMTP_USER is the same as SMTP_FROM
      - SMTP_PASSWORD="REPLACED"
      - SMTP_PORT=587

      # Optional, but recommended for docker deployments
      - JWT_SECRET="REPLACED" # Used for JWT authentication, can be any random string
    networks:
      - Network1

networks:
  Network1:
    external: true
```

**Comment by Impre-visible** [comment]
It's fixed, it was because you were forced to set OIDC ENDPOINTS

**Comment by TheInfamousToTo** [comment]
i think new issue found 
```
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/auth/me, PATCH} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/auth/password, PATCH} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/auth/signup, POST} route +1ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/auth/login, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/auth/refresh, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/auth/logout, POST} route +1ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RoutesResolver] CompanyController {/api/company}: +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/company/info, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/company/info, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/company/pdf-template, GET} route +1ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/company/pdf-template, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/company/email-templates, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/company/email-templates, PUT} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RoutesResolver] ClientsController {/api/clients}: +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/clients, GET} route +1ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/clients/search, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/clients, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/clients/:id, PATCH} route +1ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/clients/:id, DELETE} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RoutesResolver] QuotesController {/api/quotes}: +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/quotes, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/quotes/search, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/quotes/:id/pdf, GET} route +1ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/quotes/mark-as-signed, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/quotes, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/quotes/:id, PATCH} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/quotes/:id, DELETE} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RoutesResolver] InvoicesController {/api/invoices}: +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/invoices, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/invoices/search, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id/pdf, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id/download/xml, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id/download/pdf, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/invoices/create-from-quote, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/invoices/mark-as-paid, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/invoices, POST} route +1ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/invoices/send, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id, PATCH} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id, DELETE} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RoutesResolver] ReceiptsController {/api/receipts}: +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/receipts, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/receipts/search, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/receipts/create-from-invoice, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/receipts/:id/pdf, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/receipts/send, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/receipts, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/receipts/:id, PATCH} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/receipts/:id, DELETE} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RoutesResolver] DashboardController {/api/dashboard}: +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/dashboard, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RoutesResolver] SignaturesController {/api/signatures}: +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/signatures/:id, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/signatures, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/signatures/:id/otp, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/signatures/:id/sign, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RoutesResolver] DangerController {/api/danger}: +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/danger/otp, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/danger/reset/app, POST} route +1ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/danger/reset/all, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RoutesResolver] PluginsController {/api/plugins}: +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/plugins, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/plugins/formats, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/plugins, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/plugins, DELETE} route +1ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RoutesResolver] RecurringInvoicesController {/api/recurring-invoices}: +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices/:id, GET} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices, POST} route +0ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices/:id, PATCH} route +1ms
[Nest] 93  - 07/25/2025, 2:31:30 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices/:id, DELETE} route +0ms
/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:64
${er(e)}`}var tf=N("prisma:client:engines:resolveEnginePath"),nf=()=>new RegExp("runtime[\\\\/]library\\.m?js$");async function yl(e,r){let t={binary:process.env.PRISMA_QUERY_ENGINE_BINARY,library:process.env.PRISMA_QUERY_ENGINE_LIBRARY}[e]??r.prismaPath;if(t!==void 0)return t;let{enginePath:n,searchedLocations:i}=await of(e,r);if(tf("enginePath",n),n!==void 0&&e==="binary"&&Si(n),n!==void 0)return r.prismaPath=n;let o=await ir(),s=r.generator?.binaryTargets??[],a=s.some(d=>d.native),l=!s.some(d=>d.value===o),u=__filename.match(nf())===null,c={searchedLocations:i,generatorBinaryTargets:s,generator:r.generator,runtimeBinaryTarget:o,queryEngineName:bl(e,o),expectedLocation:St.default.relative(process.cwd(),r.dirname),errorStack:new Error().stack},p;throw a&&l?p=fl(c):l?p=dl(c):u?p=ml(c):p=gl(c),new T(p,r.clientVersion)}async function of(e,r){let t=await ir(),n=[],i=[r.dirname,St.default.resolve(__dirname,".."),r.generator?.output?.value??__dirname,St.default.resolve(__dirname,"../../../.prisma/client"),"/tmp/prisma-engines",r.cwd];__filename.includes("resolveEnginePath")&&i.push(fs());for(let o of i){let s=bl(e,t),a=St.default.join(o,s);if(n.push(o),hl.default.existsSync(a))return{enginePath:a,searchedLocations:n}}return{enginePath:void 0,searchedLocations:n}}function bl(e,r){return e==="library"?Gt(r,"fs"):`query-engine-${r}${r==="windows"?".exe":""}`}var co=A(_i());function El(e){return e?e.replace(/".*"/g,'"X"').replace(/[\s:\[]([+-]?([0-9]*[.])?[0-9]+)/g,r=>`${r[0]}5`):""}function wl(e){return e.split(`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ^
PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "linux-musl-openssl-3.0.x".
This happened because Prisma Client was generated for "debian-openssl-1.1.x", but the actual deployment required "linux-musl-openssl-3.0.x".
Add "linux-musl-openssl-3.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl-openssl-3.0.x"]
}
The following locations have been searched:
  /usr/share/nginx/backend/node_modules/.prisma/client
  /usr/share/nginx/backend/node_modules/@prisma/client
  /app/node_modules/@prisma/client
  /tmp/prisma-engines
  /usr/share/nginx/backend/prisma
    at yl (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:64:805)
    at async Object.loadLibrary (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:111:7966)
    at async Gr.loadEngine (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:112:448)
    at async Gr.instantiateLibrary (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:111:11869) {
  clientVersion: '6.12.0',
  errorCode: undefined,
  retryable: undefined
}
Node.js v22.16.0
```


here is the logs

**Comment by Impre-visible** [comment]
Are you using the arm/v8 image?

**Comment by TheInfamousToTo** [comment]
im running docker on linux/amd64 processor , here is my docker compose file 
```
services:
invoicerr:
image: ghcr.io/impre-visible/invoicerr:latest
restart: unless-stopped
ports:
- "8870:80"
environment:
- DATABASE_URL=postgresql://invoicerr:invoicerr@REPLACED/invoicerr_db
  - APP_URL=https://REPLACED

  # Required for email features
  - SMTP_HOST="smtp.gmail.com"
  - SMTP_USER="REPLACED"
  - SMTP_FROM="REPLACED" # Not required if SMTP_USER is the same as SMTP_FROM
  - SMTP_PASSWORD="REPLACED"
  - SMTP_PORT=587

  # Optional, but recommended for docker deployments
  - JWT_SECRET="REPLACED" # Used for JWT authentication, can be any random string
networks:
  - Network1
```

**Comment by Impre-visible** [comment]
I think I see

**Comment by Impre-visible** [comment]
Can you retry mate

**Comment by TheInfamousToTo** [comment]
hi Mate , really apprecitate how you constantly working on the issues , 
here is the log for version 1.2.6c
```
npm WARN exec The following package was not found and will be installed: prisma
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'prisma@6.12.0',
npm WARN EBADENGINE   required: { node: '>=18.18' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm ERR! code 1
npm ERR! path /root/.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines
npm ERR! command failed
npm ERR! command sh -c node scripts/postinstall.js
npm ERR! /root/.npm/_npx/2778af9cee32ff87/node_modules/@prisma/debug/dist/index.js:115
npm ERR! globalThis.DEBUG ??= processEnv.DEBUG ?? "";
npm ERR!                   ^

 
npm ERR! SyntaxError: Unexpected token '?'
npm ERR!     at wrapSafe (internal/modules/cjs/loader.js:915:16)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:963:27)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:74:18)
npm ERR!     at Object.<anonymous> (/root/.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/dist/scripts/postinstall.js:26:29)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2025-07-25T15_44_13_018Z-debug.log
Waiting for backend to start...
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/backend/main.js:18
    await app.listen(process.env.PORT ?? 3000);
                                       ^
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
```

**Comment by Hanibachi** [comment]
i m facing the same issue, first, the dockerfile is missing the netcat install command, and while i dont know much about js developpement , i think there's an issue with nodeJs version.
i added custom command to my compose file to install nc , but i still get the following errors:
```
invoicerr  | Hit:1 http://deb.debian.org/debian bullseye InRelease
invoicerr  | Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
invoicerr  | Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
invoicerr  | Reading package lists...
invoicerr  | Reading package lists...
invoicerr  | Building dependency tree...
invoicerr  | Reading state information...
invoicerr  | The following additional packages will be installed:
invoicerr  |   netcat-openbsd
invoicerr  | The following NEW packages will be installed:
invoicerr  |   netcat netcat-openbsd
invoicerr  | 0 upgraded, 2 newly installed, 0 to remove and 44 not upgraded.
invoicerr  | Need to get 50.3 kB of archives.
invoicerr  | After this operation, 122 kB of additional disk space will be used.
invoicerr  | Get:1 http://deb.debian.org/debian bullseye/main arm64 netcat-openbsd arm64 1.217-3 [40.5 kB]
invoicerr  | Get:2 http://deb.debian.org/debian bullseye/main arm64 netcat all 1.10-46 [9728 B]
invoicerr  | debconf: delaying package configuration, since apt-utils is not installed
invoicerr  | Fetched 50.3 kB in 0s (2939 kB/s)
invoicerr  | Selecting previously unselected package netcat-openbsd.
(Reading database ... 35513 files and directories currently installed.)
invoicerr  | Preparing to unpack .../netcat-openbsd_1.217-3_arm64.deb ...
invoicerr  | Unpacking netcat-openbsd (1.217-3) ...
invoicerr  | Selecting previously unselected package netcat.
invoicerr  | Preparing to unpack .../netcat_1.10-46_all.deb ...
invoicerr  | Unpacking netcat (1.10-46) ...
invoicerr  | Setting up netcat-openbsd (1.217-3) ...
invoicerr  | update-alternatives: using /bin/nc.openbsd to provide /bin/nc (nc) in auto mode
invoicerr  | update-alternatives: warning: skip creation of /usr/share/man/man1/nc.1.gz because associated file /usr/share/man/man1/nc_openbsd.1.gz (of link group nc) doesn't exist
invoicerr  | update-alternatives: warning: skip creation of /usr/share/man/man1/netcat.1.gz because associated file /usr/share/man/man1/nc_openbsd.1.gz (of link group nc) doesn't exist
invoicerr  | Setting up netcat (1.10-46) ...
invoicerr  | npm WARN exec The following package was not found and will be installed: prisma
invoicerr  | npm WARN EBADENGINE Unsupported engine {
invoicerr  | npm WARN EBADENGINE   package: 'prisma@6.12.0',
invoicerr  | npm WARN EBADENGINE   required: { node: '>=18.18' },
invoicerr  | npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
invoicerr  | npm WARN EBADENGINE }
invoicerr  | npm ERR! code 1
invoicerr  | npm ERR! path /root/.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines
invoicerr  | npm ERR! command failed
invoicerr  | npm ERR! command sh -c node scripts/postinstall.js
invoicerr  | npm ERR! /root/.npm/_npx/2778af9cee32ff87/node_modules/@prisma/debug/dist/index.js:115
invoicerr  | npm ERR! globalThis.DEBUG ??= processEnv.DEBUG ?? "";
invoicerr  | npm ERR!                   ^
invoicerr  | npm ERR! 
invoicerr  | npm ERR! SyntaxError: Unexpected token '?'
invoicerr  | npm ERR!     at wrapSafe (internal/modules/cjs/loader.js:915:16)
invoicerr  | npm ERR!     at Module._compile (internal/modules/cjs/loader.js:963:27)
invoicerr  | npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
invoicerr  | npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
invoicerr  | npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
invoicerr  | npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
invoicerr  | npm ERR!     at require (internal/modules/cjs/helpers.js:74:18)
invoicerr  | npm ERR!     at Object.<anonymous> (/root/.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/dist/scripts/postinstall.js:26:29)
invoicerr  | npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
invoicerr  | npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
invoicerr  | 
invoicerr  | npm ERR! A complete log of this run can be found in:
invoicerr  | npm ERR!     /root/.npm/_logs/2025-07-25T15_49_34_271Z-debug.log
invoicerr  | Waiting for backend to start...
invoicerr  | /usr/share/nginx/backend/main.js:18
invoicerr  |     await app.listen(process.env.PORT ?? 3000);
invoicerr  |                                        ^
invoicerr  | 
invoicerr  | SyntaxError: Unexpected token '?'
invoicerr  |     at wrapSafe (internal/modules/cjs/loader.js:915:16)
invoicerr  |     at Module._compile (internal/modules/cjs/loader.js:963:27)
invoicerr  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
invoicerr  |     at Module.load (internal/modules/cjs/loader.js:863:32)
invoicerr  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
invoicerr  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
invoicerr  |     at internal/main/run_main_module.js:17:47

```

**Comment by Impre-visible** [comment]
It's an issue with the nginx image I used, it was way to old, sorry

**Comment by TheInfamousToTo** [comment]
here is the logs on 1.2.6d

```
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/invoices, GET} route +1ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/invoices/search, GET} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id/pdf, GET} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id/download/xml, GET} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id/download/pdf, GET} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/invoices/create-from-quote, POST} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/invoices/mark-as-paid, POST} route +1ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/invoices, POST} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/invoices/send, POST} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id, PATCH} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id, DELETE} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RoutesResolver] ReceiptsController {/api/receipts}: +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/receipts, GET} route +1ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/receipts/search, GET} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/receipts/create-from-invoice, POST} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/receipts/:id/pdf, GET} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/receipts/send, POST} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/receipts, POST} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/receipts/:id, PATCH} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/receipts/:id, DELETE} route +1ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RoutesResolver] DashboardController {/api/dashboard}: +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/dashboard, GET} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RoutesResolver] SignaturesController {/api/signatures}: +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/signatures/:id, GET} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/signatures, POST} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/signatures/:id/otp, POST} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/signatures/:id/sign, POST} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RoutesResolver] DangerController {/api/danger}: +1ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/danger/otp, POST} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/danger/reset/app, POST} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/danger/reset/all, POST} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RoutesResolver] PluginsController {/api/plugins}: +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/plugins, GET} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/plugins/formats, GET} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/plugins, POST} route +1ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/plugins, DELETE} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RoutesResolver] RecurringInvoicesController {/api/recurring-invoices}: +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices, GET} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices/:id, GET} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices, POST} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices/:id, PATCH} route +0ms
[Nest] 88  - 07/25/2025, 4:24:13 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices/:id, DELETE} route +1ms
/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:64
${er(e)}`}var tf=N("prisma:client:engines:resolveEnginePath"),nf=()=>new RegExp("runtime[\\\\/]library\\.m?js$");async function yl(e,r){let t={binary:process.env.PRISMA_QUERY_ENGINE_BINARY,library:process.env.PRISMA_QUERY_ENGINE_LIBRARY}[e]??r.prismaPath;if(t!==void 0)return t;let{enginePath:n,searchedLocations:i}=await of(e,r);if(tf("enginePath",n),n!==void 0&&e==="binary"&&Si(n),n!==void 0)return r.prismaPath=n;let o=await ir(),s=r.generator?.binaryTargets??[],a=s.some(d=>d.native),l=!s.some(d=>d.value===o),u=__filename.match(nf())===null,c={searchedLocations:i,generatorBinaryTargets:s,generator:r.generator,runtimeBinaryTarget:o,queryEngineName:bl(e,o),expectedLocation:St.default.relative(process.cwd(),r.dirname),errorStack:new Error().stack},p;throw a&&l?p=fl(c):l?p=dl(c):u?p=ml(c):p=gl(c),new T(p,r.clientVersion)}async function of(e,r){let t=await ir(),n=[],i=[r.dirname,St.default.resolve(__dirname,".."),r.generator?.output?.value??__dirname,St.default.resolve(__dirname,"../../../.prisma/client"),"/tmp/prisma-engines",r.cwd];__filename.includes("resolveEnginePath")&&i.push(fs());for(let o of i){let s=bl(e,t),a=St.default.join(o,s);if(n.push(o),hl.default.existsSync(a))return{enginePath:a,searchedLocations:n}}return{enginePath:void 0,searchedLocations:n}}function bl(e,r){return e==="library"?Gt(r,"fs"):`query-engine-${r}${r==="windows"?".exe":""}`}var co=A(_i());function El(e){return e?e.replace(/".*"/g,'"X"').replace(/[\s:\[]([+-]?([0-9]*[.])?[0-9]+)/g,r=>`${r[0]}5`):""}function wl(e){return e.split(`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ^
PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "debian-openssl-3.0.x".
This happened because Prisma Client was generated for "debian-openssl-1.1.x", but the actual deployment required "debian-openssl-3.0.x".
Add "debian-openssl-3.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-3.0.x"]
}
The following locations have been searched:
  /usr/share/nginx/backend/node_modules/.prisma/client
  /usr/share/nginx/backend/node_modules/@prisma/client
  /app/node_modules/@prisma/client
  /tmp/prisma-engines
  /usr/share/nginx/backend/prisma
    at yl (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:64:805)
    at async Object.loadLibrary (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:111:7966)
    at async Gr.loadEngine (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:112:448)
    at async Gr.instantiateLibrary (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:111:11869)
    at async Gr.start (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:112:2155)
    at async Proxy.onModuleInit (/usr/share/nginx/backend/prisma/prisma.service.js:15:9)
    at async Promise.all (index 0)
    at async callModuleInitHook (/usr/share/nginx/backend/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)
    at async NestApplication.callInitHook (/usr/share/nginx/backend/node_modules/@nestjs/core/nest-application-context.js:242:13)
    at async NestApplication.init (/usr/share/nginx/backend/node_modules/@nestjs/core/nest-application.js:103:9) {
  clientVersion: '6.12.0',
  errorCode: undefined,
  retryable: undefined
}
Node.js v22.17.1
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
```

**Comment by Impre-visible** [comment]
Can you try the latest version v1.2.6e, it should have resolved the issue

**Comment by TheInfamousToTo** [comment]
no luck
```
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/company/info, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/company/info, POST} route +1ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/company/pdf-template, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/company/pdf-template, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/company/email-templates, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/company/email-templates, PUT} route +1ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RoutesResolver] ClientsController {/api/clients}: +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/clients, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/clients/search, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/clients, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/clients/:id, PATCH} route +1ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/clients/:id, DELETE} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RoutesResolver] QuotesController {/api/quotes}: +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/quotes, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/quotes/search, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/quotes/:id/pdf, GET} route +1ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/quotes/mark-as-signed, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/quotes, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/quotes/:id, PATCH} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/quotes/:id, DELETE} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RoutesResolver] InvoicesController {/api/invoices}: +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/invoices, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/invoices/search, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id/pdf, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id/download/xml, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id/download/pdf, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/invoices/create-from-quote, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/invoices/mark-as-paid, POST} route +1ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/invoices, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/invoices/send, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id, PATCH} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/invoices/:id, DELETE} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RoutesResolver] ReceiptsController {/api/receipts}: +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/receipts, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/receipts/search, GET} route +1ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/receipts/create-from-invoice, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/receipts/:id/pdf, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/receipts/send, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/receipts, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/receipts/:id, PATCH} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/receipts/:id, DELETE} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RoutesResolver] DashboardController {/api/dashboard}: +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/dashboard, GET} route +1ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RoutesResolver] SignaturesController {/api/signatures}: +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/signatures/:id, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/signatures, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/signatures/:id/otp, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/signatures/:id/sign, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RoutesResolver] DangerController {/api/danger}: +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/danger/otp, POST} route +1ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/danger/reset/app, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/danger/reset/all, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RoutesResolver] PluginsController {/api/plugins}: +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/plugins, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/plugins/formats, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/plugins, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/plugins, DELETE} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RoutesResolver] RecurringInvoicesController {/api/recurring-invoices}: +1ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices/:id, GET} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices, POST} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices/:id, PATCH} route +0ms
[Nest] 88  - 07/25/2025, 5:02:32 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices/:id, DELETE} route +0ms
/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:64
${er(e)}`}var tf=N("prisma:client:engines:resolveEnginePath"),nf=()=>new RegExp("runtime[\\\\/]library\\.m?js$");async function yl(e,r){let t={binary:process.env.PRISMA_QUERY_ENGINE_BINARY,library:process.env.PRISMA_QUERY_ENGINE_LIBRARY}[e]??r.prismaPath;if(t!==void 0)return t;let{enginePath:n,searchedLocations:i}=await of(e,r);if(tf("enginePath",n),n!==void 0&&e==="binary"&&Si(n),n!==void 0)return r.prismaPath=n;let o=await ir(),s=r.generator?.binaryTargets??[],a=s.some(d=>d.native),l=!s.some(d=>d.value===o),u=__filename.match(nf())===null,c={searchedLocations:i,generatorBinaryTargets:s,generator:r.generator,runtimeBinaryTarget:o,queryEngineName:bl(e,o),expectedLocation:St.default.relative(process.cwd(),r.dirname),errorStack:new Error().stack},p;throw a&&l?p=fl(c):l?p=dl(c):u?p=ml(c):p=gl(c),new T(p,r.clientVersion)}async function of(e,r){let t=await ir(),n=[],i=[r.dirname,St.default.resolve(__dirname,".."),r.generator?.output?.value??__dirname,St.default.resolve(__dirname,"../../../.prisma/client"),"/tmp/prisma-engines",r.cwd];__filename.includes("resolveEnginePath")&&i.push(fs());for(let o of i){let s=bl(e,t),a=St.default.join(o,s);if(n.push(o),hl.default.existsSync(a))return{enginePath:a,searchedLocations:n}}return{enginePath:void 0,searchedLocations:n}}function bl(e,r){return e==="library"?Gt(r,"fs"):`query-engine-${r}${r==="windows"?".exe":""}`}var co=A(_i());function El(e){return e?e.replace(/".*"/g,'"X"').replace(/[\s:\[]([+-]?([0-9]*[.])?[0-9]+)/g,r=>`${r[0]}5`):""}function wl(e){return e.split(`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ^
PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "debian-openssl-3.0.x".
This happened because Prisma Client was generated for "debian-openssl-1.1.x", but the actual deployment required "debian-openssl-3.0.x".
Add "debian-openssl-3.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-3.0.x"]
}
The following locations have been searched:
  /usr/share/nginx/backend/node_modules/.prisma/client
  /usr/share/nginx/backend/node_modules/@prisma/client
  /app/node_modules/@prisma/client
  /tmp/prisma-engines
  /usr/share/nginx/backend/prisma
    at yl (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:64:805)
    at async Object.loadLibrary (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:111:7966)
    at async Gr.loadEngine (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:112:448)
    at async Gr.instantiateLibrary (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:111:11869) {
  clientVersion: '6.12.0',
  errorCode: undefined,
  retryable: undefined
}
Node.js v22.17.1
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found
/usr/share/nginx/entrypoint.sh: 10: nc: not found

```

**Comment by Impre-visible** [comment]
finally, the v1.2.6f should do the trick, it runs for me perfectly

**Comment by Impre-visible** [comment]
Hi, does that work for you?

**Comment by jaykayenn** [comment]
Just pulled latest. Cannot setup initial company info. Save button kicks me out to login screen. No errors output to console.

**Comment by Hanibachi** [comment]
this is all i get
```
invoicerr  | /usr/local/bin/node: 1: Syntax error: "(" unexpected
invoicerr  | Waiting for backend to start...
invoicerr  | /usr/share/nginx/entrypoint.sh: 8: node: Exec format error
```

**Comment by Impre-visible** [comment]
What the heck??? How's that possible, it runs perfectly for me... I'm gonna take a look

**Comment by TheInfamousToTo** [comment]
im unable to login 
here is the logs
192.168.31.46 - - [27/Jul/2025:21:56:47 +0000] "GET /api/auth/me HTTP/1.1" 401 93 "http://192.168.31.10:8870/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "-"
192.168.31.46 - - [27/Jul/2025:21:56:46 +0000] "POST /api/auth/login HTTP/1.1" 201 32 "http://192.168.31.10:8870/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "-"

**Comment by Impre-visible** [comment]
Sadly the logs don't tell use anything interesting lol 😂 I'm gonna take a look at that asap

**Comment by Impre-visible** [comment]
Ok, I invite you to try the [v1.2.6g](https://github.com/Impre-visible/invoicerr/releases/tag/v1.2.6g) version.

I patched the bug with the company info form that "disconnects" the user.

**Comment by TheInfamousToTo** [comment]
hi mate , sorry but still not working 
i think now logs are useful
```
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/receipts/:id/pdf, GET} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/receipts/send, POST} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/receipts, POST} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/receipts/:id, PATCH} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/receipts/:id, DELETE} route +1ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RoutesResolver] DashboardController {/api/dashboard}: +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/dashboard, GET} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RoutesResolver] SignaturesController {/api/signatures}: +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/signatures/:id, GET} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/signatures, POST} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/signatures/:id/otp, POST} route +1ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/signatures/:id/sign, POST} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RoutesResolver] DangerController {/api/danger}: +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/danger/otp, POST} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/danger/reset/app, POST} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/danger/reset/all, POST} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RoutesResolver] PluginsController {/api/plugins}: +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/plugins, GET} route +1ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/plugins/formats, GET} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/plugins, POST} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/plugins, DELETE} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RoutesResolver] RecurringInvoicesController {/api/recurring-invoices}: +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices, GET} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices/:id, GET} route +1ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices, POST} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices/:id, PATCH} route +0ms
[Nest] 63  - 07/28/2025, 3:36:51 PM     LOG [RouterExplorer] Mapped {/api/recurring-invoices/:id, DELETE} route +0ms
[Nest] 63  - 07/28/2025, 3:36:52 PM     LOG [NestApplication] Nest application successfully started +1012ms
[Nest] 63  - 07/28/2025, 3:37:11 PM   ERROR [ExceptionsHandler] PrismaClientKnownRequestError: 
Invalid `this.quote.findMany()` invocation in
/usr/share/nginx/backend/prisma/prisma.service.js:23:45
  20 if (['Quote', 'Invoice', 'Receipt'].includes(params.model || '') && params.action === 'update') {
  21     return next(params);
  22 }
→ 23 let toUpdate = await this.quote.findMany(
The table `public.Quote` does not exist in the current database.
    at ri.handleRequestError (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:121:7459)
    at ri.handleAndLogRequestError (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:121:6784)
    at ri.request (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:121:6491)
    at async l (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:130:9812)
    at async /usr/share/nginx/backend/prisma/prisma.service.js:23:28
    at async AuthService.signUp (/usr/share/nginx/backend/models/auth/auth.service.js:87:13)
    at async /usr/share/nginx/backend/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /usr/share/nginx/backend/node_modules/@nestjs/core/router/router-proxy.js:9:17 {
  code: 'P2021',

{
    modelName: 'Quote',
    table: 'public.Quote'
  },
  clientVersion: '6.12.0'
}
[Nest] 63  - 07/28/2025, 3:37:14 PM   ERROR [ExceptionsHandler] PrismaClientKnownRequestError: 
Invalid `this.quote.findMany()` invocation in
/usr/share/nginx/backend/prisma/prisma.service.js:23:45
  20 if (['Quote', 'Invoice', 'Receipt'].includes(params.model || '') && params.action === 'update') {
  21     return next(params);
  22 }
→ 23 let toUpdate = await this.quote.findMany(
The table `public.Quote` does not exist in the current database.
    at ri.handleRequestError (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:121:7459)
    at ri.handleAndLogRequestError (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:121:6784)
    at ri.request (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:121:6491)
    at async l (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:130:9812)
    at async /usr/share/nginx/backend/prisma/prisma.service.js:23:28
    at async AuthService.signUp (/usr/share/nginx/backend/models/auth/auth.service.js:87:13)
    at async /usr/share/nginx/backend/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /usr/share/nginx/backend/node_modules/@nestjs/core/router/router-proxy.js:9:17 {
  code: 'P2021',

{
    modelName: 'Quote',
    table: 'public.Quote'
  },
  clientVersion: '6.12.0'
}
[Nest] 63  - 07/28/2025, 3:37:17 PM   ERROR [ExceptionsHandler] PrismaClientKnownRequestError: 
Invalid `this.quote.findMany()` invocation in
/usr/share/nginx/backend/prisma/prisma.service.js:23:45
  20 if (['Quote', 'Invoice', 'Receipt'].includes(params.model || '') && params.action === 'update') {
  21     return next(params);
  22 }
→ 23 let toUpdate = await this.quote.findMany(
The table `public.Quote` does not exist in the current database.
    at ri.handleRequestError (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:121:7459)
    at ri.handleAndLogRequestError (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:121:6784)
    at ri.request (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:121:6491)
    at async l (/usr/share/nginx/backend/node_modules/@prisma/client/runtime/library.js:130:9812)
    at async /usr/share/nginx/backend/prisma/prisma.service.js:23:28
    at async AuthService.signUp (/usr/share/nginx/backend/models/auth/auth.service.js:87:13)
    at async /usr/share/nginx/backend/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /usr/share/nginx/backend/node_modules/@nestjs/core/router/router-proxy.js:9:17 {
  code: 'P2021',

{
    modelName: 'Quote',
    table: 'public.Quote'
  },
  clientVersion: '6.12.0'
}
```

**Comment by Impre-visible** [comment]
Did you reset your database by any chance? It means that your "public" schema is empty, like if you removed things

**Comment by TheInfamousToTo** [comment]
yep , i have drop the db to startover ( part of trying to know what was the issue 0
but shouldnt this be part of initialization ?

**Comment by Impre-visible** [comment]
It should, can you completely restart your container?

**Comment by TheInfamousToTo** [comment]
i got that fixed (i didnt give the correct permission on DB ), but still the login issue exist 
once i click login it show notification of login success but it doesn't log me in !
unfortunately i dont see any logs for this

**Comment by Impre-visible** [comment]
I'm gonna work on that for the next hours, I'll come back when it's fixes

**Comment by jaykayenn** [comment]
> Ok, I invite you to try the [v1.2.6g](https://github.com/Impre-visible/invoicerr/releases/tag/v1.2.6g) version.
> 
> I patched the bug with the company info form that "disconnects" the user.

1.2.6g fixed the Company Info login issue.

**Comment by TheInfamousToTo** [comment]
hi mate , 
i found that when im using the IP address ( example 192.168.31.100:80 ) it will not log me in 
but when im using whatever im configuring in docker compose "APP_URL=https://example.theinfamoustoto.com" it will work fine 
i missed this part , apologies

**Comment by Impre-visible** [comment]
Oh i see, that's a CORS error... I'll try to fix that by allowing everything, last time I tried it broke the entire app so 😂 we'll see

**Comment by Impre-visible** [comment]
> hi mate , i found that when im using the IP address ( example 192.168.31.100:80 ) it will not log me in but when im using whatever im configuring in docker compose "APP_URL=https://example.theinfamoustoto.com" it will work fine i missed this part , apologies

I invite you to try the [v1.2.6h](https://github.com/Impre-visible/invoicerr/releases/tag/v1.2.6h) version that should solve the issue

**Comment by Impre-visible** [comment]
@TheInfamousToTo can you please try the new release so now we know if it's working or not 😄 
Thanks

**Comment by adrenalinmike** [comment]
Just updated today to the newest Docker and reset the database
invoicerr-1     | [Nest] 72  - 07/30/2025, 2:57:14 PM   ERROR [ExceptionsHandler] Error: Browser was not found at the configured executablePath (/usr/bin/chromium-browser)
invoicerr-1     |     at ChromeLauncher.launch (/usr/share/nginx/backend/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserLauncher.js:89:19)
invoicerr-1     |     at async getPDF (/usr/share/nginx/backend/utils/pdf.js:78:19)
invoicerr-1     |     at async QuotesService.getQuotePdf (/usr/share/nginx/backend/models/quotes/quotes.service.js:248:27)
invoicerr-1     |     at async QuotesController.getQuotePdf (/usr/share/nginx/backend/models/quotes/quotes.controller.js:34:27)
invoicerr-1     |     at async /usr/share/nginx/backend/node_modules/@nestjs/core/router/router-execution-context.js:46:28
invoicerr-1     |     at async /usr/share/nginx/backend/node_modules/@nestjs/core/router/router-proxy.js:9:17

No pdf anymore

**Comment by Impre-visible** [comment]
I think I see the issue

**Comment by TheInfamousToTo** [comment]
hi mate , still the same case 
cant access from the IP only from "APP_URL="
i have not test most of the functionalities but i have test view PDF and facing some issue , here is the logs 
```
[Nest] 83  - 07/30/2025, 4:19:24 PM   ERROR [ExceptionsHandler] Error: Browser was not found at the configured executablePath (/usr/bin/chromium-browser)
    at async getPDF (/usr/share/nginx/backend/utils/pdf.js:78:19)
    at ChromeLauncher.launch (/usr/share/nginx/backend/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserLauncher.js:89:19)
    at async QuotesService.getQuotePdf (/usr/share/nginx/backend/models/quotes/quotes.service.js:248:27)
    at async QuotesController.getQuotePdf (/usr/share/nginx/backend/models/quotes/quotes.controller.js:34:27)
    at async /usr/share/nginx/backend/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /usr/share/nginx/backend/node_modules/@nestjs/core/router/router-proxy.js:9:17
[Nest] 83  - 07/30/2025, 4:19:35 PM   ERROR [ExceptionsHandler] Error: Browser was not found at the configured executablePath (/usr/bin/chromium-browser)

```

**Comment by Impre-visible** [comment]
Okay, I'll have to work a bit harder on that CORS issue... One possible things would be to ask the user to provide an array of URLs that are allowed (the various IP/URLs used to access the app)

**Comment by TheInfamousToTo** [comment]
well , to me its not major issue if you know about it 
yet as you mention an array will be easy and quick fix

**Comment by jaykayenn** [comment]
> Okay, I'll have to work a bit harder on that CORS issue... One possible things would be to ask the user to provide an array of URLs that are allowed (the various IP/URLs used to access the app)

Once APP_URL is set, CORS should correctly only allow that URL. Direct local access should be handled by local DNS/router. 
If you really want to add more CORS destinations, I suggest a new env option, leave the APP_URL as is.

**Comment by Impre-visible** [comment]
> > Okay, I'll have to work a bit harder on that CORS issue... One possible things would be to ask the user to provide an array of URLs that are allowed (the various IP/URLs used to access the app)
> 
> Once APP_URL is set, CORS should correctly only allow that URL. Direct local access should be handled by local DNS/router. If you really want to add more CORS destinations, I suggest a new env option, leave the APP_URL as is.

It's currently the case, but if APP_URL is the public domain name and you want to use it locally you can't... So I'm gonna add a new "CORS_URLS" that take an array of URL/ip:port to add them to the cors

**Comment by Impre-visible** [comment]
Here you go, you can try the v1.2.6l, you can set the env ``CORS_ORIGINS`` to a list of urls/ip:port (separated with commas)

**Comment by TheInfamousToTo** [comment]
i have added ```      - CORS_ORIGINS=192.168.31.10:8870``` but still same , unable to access from the IP
for the PDF part . its working fine now

**Comment by Impre-visible** [comment]
But that works when accessing the site from the APP_URL url?

**Comment by jaykayenn** [comment]
Is CORS_ORIGINS required and separate from APP_URL now?

**Comment by Impre-visible** [comment]
CORS_ORIGINS is not required, and is separate from APP_URL as APP_URL is necessary (not required, but it's better to have it)

**Comment by adrenalinmike** [comment]
1.2.6m works for PDF creation 
Thank you for the swift fix
I switched for now from :latest to  versioning (:1.2.6m) to avoid hickups

**Comment by Hanibachi** [comment]
this is still an issue with `v1.2.6h` and it's still set to be latest

```
invoicerr  | Waiting for backend to start...
invoicerr  | /usr/local/bin/node: 1: Syntax error: "(" unexpected
invoicerr  | /usr/share/nginx/entrypoint.sh: 8: node: Exec format error
```

edit : same issue with `1.2.6m` confirmed

**Comment by Impre-visible** [comment]
You are right, the v1.2.6 is flagged as the latest, as the v1.2.6n should be the right one

**Comment by Hanibachi** [comment]
am i the only one getting the nodejs syntax error ???? even with `v1.2.6n`

**Comment by Impre-visible** [comment]
What's your image arch? amd64 or arm64? I only see that, as the v1.2.6n run well for me

**Comment by Hanibachi** [comment]
arm64, but i dont see why the architecture should affect something like this

**Comment by Impre-visible** [comment]
That the difference with me, I'm on amd64 and that runs well for me, so I guess that's why you go the error

**Comment by Hanibachi** [comment]
i have indeed confirmed that the issue was because of the architecture.
it's working fine on a amd64 machine.
 a bit weird but i hope this can be fixed.

**Comment by Impre-visible** [comment]
I'll have to take a good look at that, hope so

**Comment by Impre-visible** [comment]
@Hanibachi can you try the [v1.2.6q](https://github.com/users/Impre-visible/packages/container/invoicerr/476986993?tag=v1.2.6q) please, that should have resolved the issue

**Comment by Impre-visible** [comment]
Hi, the v1.3.0 should solve the issue
