### ISSUE TITLE
OIDC JWKS errors on startup even without OIDC configuration

### ISSUE THREAD

**Issue by baptistebca** [Impre-visible/invoicerr#148]
**Describe the bug**
Application fails to start properly with repeated TypeError: Invalid URL errors during OIDC JWKS initialization, even when no OIDC variables are configured.

**Environment**

- Docker Compose
- Image: ghcr.io/impre-visible/invoicerr:latest
- PostgreSQL database

**Configuration**
Minimal docker-compose.yml with no OIDC variables:

`services:
  invoicerr:
    image: ghcr.io/impre-visible/invoicerr:latest
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://invoicerr:invoicerr@db:5432/invoicerr_db
      - APP_URL=http://localhost:8000
      - JWT_SECRET=test_secret`

** Error logs"

`[Nest] 72  - 08/29/2025, 7:51:27 AM   ERROR [TypeError: Invalid URL] Failed to create JWKS set:
[Nest] 72  - 08/29/2025, 7:51:27 AM   ERROR [TypeError: Invalid URL] Failed to create JWKS set:`

**Expected behavior**
Application should start without OIDC errors when no OIDC configuration is provided.

**Actual behavior**

- Application starts but logs OIDC JWKS errors repeatedly
- Login page shows infinite redirect loop after authentication
- Database and API routes work correctly

**Workaround attempted**
Setting empty OIDC variables still produces the same error.

**Note to maintainers**
This appears to be the same issue as #111. If confirmed as duplicate, please merge/close accordingly.
The core problem seems identical: latest Docker image producing OIDC initialization errors regardless of configuration.

**Comment by Impre-visible** [comment]
Hi, the [v1.2.7a](https://github.com/Impre-visible/invoicerr/releases/tag/v1.2.7a) should solve the issue

**Comment by baptistebca** [comment]
Hello,

The latest public Docker image (`ghcr.io/impre-visible/invoicerr:latest`, corresponding to release v1.2.7) fails to start due to an authentication module error.

---
#### Error Message at Startup

The container log shows the following fatal error immediately on startup, which prevents the application from initializing correctly:

[Nest] ERROR [TypeError: Invalid URL] Failed to create JWKS set:


---
#### My `docker-compose.yml`

```yaml
services:
  invoicerr:
    image: ghcr.io/impre-visible/invoicerr:latest
    ports:
      - "8000:80"
    environment:
      - APP_URL=http://MyIP:8000
      - JWT_SECRET=MySecretKeyHere
      - DATABASE_URL=postgresql://invoicerr:invoicerr@invoicerr_db:5432/invoicerr_db
    depends_on:
      - invoicerr_db

  invoicerr_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: invoicerr
      POSTGRES_PASSWORD: invoicerr
      POSTGRES_DB: invoicerr_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
```


I am using a minimal configuration file. The error occurs even with no OIDC variables present (With and without)


Troubleshooting Steps Taken
Forced re-pull of the :latest and :main images.

Confirmed the issue is not related to local Docker caching.

Confirmed the database container starts correctly.

Building from the v1.2.7 source ZIP also fails (with a different, compile-time error).

It seems the build process for the public Docker image for v1.2.7 is broken.

Thank you

**Comment by Impre-visible** [comment]
Can you retry with that version:

```yaml
services:
  invoicerr:
    image: ghcr.io/impre-visible/invoicerr:v1.2.7a
    ports:
      - "8000:80"
    environment:
      - APP_URL=http://MyIP:8000
      - JWT_SECRET=MySecretKeyHere
      - DATABASE_URL=postgresql://invoicerr:invoicerr@invoicerr_db:5432/invoicerr_db
    depends_on:
      - invoicerr_db

  invoicerr_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: invoicerr
      POSTGRES_PASSWORD: invoicerr
      POSTGRES_DB: invoicerr_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
```

**Comment by baptistebca** [comment]
Hello,

Thank you for the quick patch with `v1.2.7a`. I can confirm that this new image **successfully fixes the startup error** (`TypeError: Invalid URL`). The application now starts correctly.

However, a login loop issue still persists. After submitting credentials on the login/signup page, the browser makes a request to `/api/auth/me` which fails with a `401 (Unauthorized)` error, preventing the login from completing.

---
#### Key Error in Browser Console

GET http://<your_ip>:8000/api/auth/me 401 (Unauthorized)


---
#### Troubleshooting Steps Taken

This is not a configuration or cache issue. I have confirmed the following:
- The server logs are clean with no errors.
- The issue occurs in **Incognito/Private mode**, ruling out browser cache and cookies.
- I have generated a **brand new `JWT_SECRET`** using `openssl rand -base64 32` and restarted the services to ensure there is no key mismatch.

The problem seems to be within the application's logic for validating the token on the `/api/auth/me` route immediately after a successful login.

#### My `docker-compose.yml`

```yaml
services:
  invoicerr:
    image: ghcr.io/impre-visible/invoicerr:v1.2.7a
    ports:
      - "8000:80"
    environment:
      - APP_URL=http://<your_ip>:8000
      - JWT_SECRET=MyFreshlyGeneratedSecretKey
      - DATABASE_URL=postgresql://invoicerr:invoicerr@invoicerr_db:5432/invoicerr_db
    depends_on:
      - invoicerr_db

  invoicerr_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: invoicerr
      POSTGRES_PASSWORD: invoicerr
      POSTGRES_DB: invoicerr_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
```
Thanks for looking into this.

**Comment by baptistebca** [comment]
I'll try a fresh install. 
I may have broken things with the previous errors. 
It's in progress, I'll keep you posted.

**Comment by baptistebca** [comment]
Hello,

Even with a completely clean installation, I am experiencing a persistent login loop with version `v1.2.7a`.

I set up a brand new Proxmox LXC container (privileged, with AppArmor unconfined) and installed Docker and the Invoicerr application from scratch. The container logs show a perfect startup with no errors.

However, after submitting credentials on the login/signup page, the application gets stuck in a loop. The browser's network tools show that the request to `/api/auth/me` fails with a `401 (Unauthorized)` error.

This test was performed on a completely new browser (Safari) that had never accessed the application before, confirming this is not a client-side caching issue.

---
#### **Environment**

- **Host:** Proxmox VE
- **Virtualization:** Privileged LXC Container
- **OS inside LXC:** Debian/Ubuntu with Docker
- **Invoicerr Version:** `v1.2.7a` (Docker Image)

**Comment by Impre-visible** [comment]
Hi, Thanks for the information, I'll take a look at that tomorrow. It's possibily an error in the auth flow, so I'll retry that on a clean and fresh install

**Comment by Impre-visible** [comment]
Hi @baptistebca I released the v1.2.9n that should solve some issues, let me know if the issue persist or if it's solved. Thanks

**Comment by baptistebca** [comment]
Thanks! 
Got it up and running, though I hit a snag with HTTP.
https://github.com/Impre-visible/invoicerr/issues/184

Excited to test it out! :)
